"""
ml/training/train_placer.py

Trains the ML luminaire placement classifier.

The model predicts luminaire TYPE (A / AW / C / E) for each candidate
position generated by ceiling_grid.  It replaces the rule-based wall-relation
logic in real_placer._place_sales().

Data sources (combinable):
  --bootstrap    Run reference DXF files through the geometric pipeline and
                 save the outputs as training samples (uses current rules as
                 teacher).  This is the first-time bootstrap.
  --annotations  Load JSONL file written by real_placer at inference time
                 (path: data/annotations/placements.jsonl).
  --synthetic    Generate synthetic samples from known feature distributions
                 when real data is scarce (<200 samples).

Usage:
  python ml/training/train_placer.py --bootstrap
  python ml/training/train_placer.py --annotations data/annotations/placements.jsonl
  python ml/training/train_placer.py --bootstrap --annotations data/annotations/placements.jsonl
"""
from __future__ import annotations
import argparse, json, pickle, sys
from pathlib import Path

import numpy as np
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import MODELS_DIR, ANNOTATIONS_DIR, DWG_DIR
from services.placer.placement_features import FEATURE_DIM, LUMI_TYPES

PLACER_MODEL_PATH    = MODELS_DIR / "placer_model.pkl"
PLACEMENTS_JSONL     = ANNOTATIONS_DIR / "placements.jsonl"


# ── Bootstrap: run geometric pipeline and collect (features, type) pairs ─────

def bootstrap_from_dwg(dwg_dir: Path = DWG_DIR,
                       output_jsonl: Path = PLACEMENTS_JSONL) -> tuple:
    """
    Run the geometric pipeline on all DXF files in dwg_dir and save the
    resulting (feature_vector, luminaire_type) pairs as training samples.

    Returns (X, y) numpy arrays.
    """
    import io, contextlib
    from main import run_pipeline

    # Patch real_placer to intercept placed luminaires with features
    import services.placer.real_placer as rp

    samples: list[dict] = []

    orig_place_sales = rp.RealLuminairePlacer._place_sales

    def patched_place_sales(self, zone, plan, excl, ox, oy):
        result = orig_place_sales(self, zone, plan, excl, ox, oy)
        # After placement, re-extract features from training_buffer if populated
        buf = getattr(self, '_training_buffer', [])
        samples.extend(buf)
        self._training_buffer = []
        return result

    rp.RealLuminairePlacer._place_sales = patched_place_sales

    dxf_files = sorted(dwg_dir.glob("*_converted.dxf"))
    # Prefer the most recent copy of each unique store name
    seen: dict[str, Path] = {}
    for f in dxf_files:
        # Strip the leading hash prefix to get the canonical name
        parts = f.stem.split("_", 1)
        key = parts[1] if len(parts) > 1 else f.stem
        seen[key] = f
    targets = list(seen.values())

    print(f"Bootstrap: processing {len(targets)} DXF file(s) …")
    for dxf in targets:
        print(f"  → {dxf.name}")
        buf = io.StringIO()
        try:
            with contextlib.redirect_stdout(buf):
                run_pipeline(str(dxf))
        except Exception as e:
            print(f"    WARN: {e}")

    rp.RealLuminairePlacer._place_sales = orig_place_sales

    if not samples:
        print("  No training samples collected (placer training hooks not active).")
        print("  Hint: set COLLECT_TRAINING=1 before bootstrapping.")
        return np.empty((0, FEATURE_DIM)), []

    print(f"  Collected {len(samples)} placement samples.")

    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    with open(output_jsonl, 'a') as f:
        for s in samples:
            f.write(json.dumps(s) + "\n")
    print(f"  Saved → {output_jsonl}")

    return _jsonl_to_arrays([output_jsonl])


def _jsonl_to_arrays(paths) -> tuple:
    X, y = [], []
    for path in paths:
        p = Path(path)
        if not p.exists():
            continue
        with open(p) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                obj = json.loads(line)
                fv  = obj.get("features")
                lt  = obj.get("lumi_type")
                if fv and lt and lt in LUMI_TYPES:
                    X.append(fv)
                    y.append(lt)
    return (np.array(X, dtype=np.float32) if X else np.empty((0, FEATURE_DIM), dtype=np.float32)), y


def generate_synthetic(n_per_class: int = 400) -> tuple:
    """
    Generate synthetic training samples from known feature distributions.
    Used to bootstrap when no real data is available yet.
    """
    import random
    rng = random.Random(42)

    def rv(lo, hi): return rng.uniform(lo, hi)
    def ri(lo, hi): return rng.randint(lo, hi)

    # (feature-index → [lo, hi]) distributions per type
    # Features 0-15: existing geometry features
    # Features 16-18: NEW — shelf_depth_norm, is_wall_assortment, is_large_depth
    #
    # A  (interior): standard 47mm shelves, non-wall assortments, far from envelope
    # AW (wall):     mix of depths (47-77mm), wall assortments common, 67/77mm possible
    # C  (corner A): same profile as A
    # E  (column):   same profile as A
    DIST = {
        'A': {
            'dist_b_m': (1.5, 10.0), 'dist_g_m': (0.3, 2.0), 'dist_c_m': (5.0, 20.0),
            'is_wall': (0, 0), 'norm_x': (0.1, 0.9), 'norm_y': (0.1, 0.9),
            'area_log': (2.3, 2.9), 's_density': (0.05, 0.25), 'checkout_norm': (0, 0),
            'zt_enc': (0, 0), 'is_near_col': (0, 0), 'b_log': (0.55, 0.85),
            'g_log': (0.3, 0.6), 'n_shelv_norm': (0.2, 0.7),
            'depth_norm': (0.37, 0.57), 'is_wall_assort': (0, 0), 'is_large_depth': (0, 0),
        },
        'AW': {
            'dist_b_m': (0.0, 2.0), 'dist_g_m': (0.0, 0.6), 'dist_c_m': (5.0, 20.0),
            'is_wall': (1, 1), 'norm_x': (0.0, 1.0), 'norm_y': (0.0, 1.0),
            'area_log': (2.3, 2.9), 's_density': (0.05, 0.25), 'checkout_norm': (0, 0),
            'zt_enc': (0, 0), 'is_near_col': (0, 0), 'b_log': (0.0, 0.55),
            'g_log': (0.0, 0.3), 'n_shelv_norm': (0.2, 0.7),
            'depth_norm': (0.47, 0.77), 'is_wall_assort': (0, 1), 'is_large_depth': (0, 1),
        },
        'C': {
            'dist_b_m': (1.5, 8.0), 'dist_g_m': (0.3, 2.0), 'dist_c_m': (5.0, 20.0),
            'is_wall': (0, 0), 'norm_x': (0.0, 0.15), 'norm_y': (0.0, 0.15),
            'area_log': (2.3, 2.9), 's_density': (0.05, 0.25), 'checkout_norm': (0, 0),
            'zt_enc': (0, 0), 'is_near_col': (0, 0), 'b_log': (0.55, 0.85),
            'g_log': (0.3, 0.6), 'n_shelv_norm': (0.2, 0.7),
            'depth_norm': (0.37, 0.57), 'is_wall_assort': (0, 0), 'is_large_depth': (0, 0),
        },
        'E': {
            'dist_b_m': (1.0, 8.0), 'dist_g_m': (1.0, 5.0), 'dist_c_m': (0.1, 1.5),
            'is_wall': (0, 0), 'norm_x': (0.1, 0.9), 'norm_y': (0.1, 0.9),
            'area_log': (2.3, 2.9), 's_density': (0.05, 0.25), 'checkout_norm': (0, 0),
            'zt_enc': (0, 0), 'is_near_col': (1, 1), 'b_log': (0.4, 0.85),
            'g_log': (0.5, 0.85), 'n_shelv_norm': (0.2, 0.7),
            'depth_norm': (0.37, 0.57), 'is_wall_assort': (0, 0), 'is_large_depth': (0, 0),
        },
    }

    KEYS = ['dist_b_m','dist_g_m','dist_c_m','is_wall','norm_x','norm_y',
            'area_log','s_density','checkout_norm','zt_enc','is_near_col',
            'b_log','g_log','phase_x','phase_y','n_shelv_norm',
            'depth_norm','is_wall_assort','is_large_depth']

    X, y = [], []
    for lt, dist in DIST.items():
        for _ in range(n_per_class):
            row = []
            for k in KEYS:
                if k in ('phase_x', 'phase_y'):
                    row.append(float(rng.randint(0, 1)))
                elif k in dist:
                    lo, hi = dist[k]
                    if lo == hi:
                        row.append(float(lo))
                    else:
                        row.append(rv(lo, hi))
                else:
                    row.append(0.0)
            X.append(row)
            y.append(lt)

    idx = np.random.default_rng(42).permutation(len(X))
    return np.array(X, dtype=np.float32)[idx], [y[i] for i in idx]


# ── Training ──────────────────────────────────────────────────────────────────

def train(X: np.ndarray, y: list, save: bool = True) -> RandomForestClassifier:
    from collections import Counter
    counts = Counter(y)
    print(f"\nTraining placement model: {len(X)} samples")
    print(f"  Classes: {dict(counts)}")

    clf = RandomForestClassifier(
        n_estimators=500,
        max_depth=18,
        min_samples_leaf=2,
        max_features='sqrt',
        class_weight='balanced',
        random_state=42,
        n_jobs=-1,
    )

    if len(X) >= 20 and len(set(y)) >= 2:
        n_splits = min(5, min(counts.values()))
        if n_splits >= 2:
            cv = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
            scores = cross_val_score(clf, X, y, cv=cv, scoring='f1_macro')
            print(f"  CV F1-macro: {scores.mean():.3f} ± {scores.std():.3f}")

    clf.fit(X, y)

    if len(X) >= 40 and len(set(y)) >= 2:
        from sklearn.model_selection import train_test_split
        try:
            Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2,
                                                    stratify=y, random_state=99)
            eval_clf = RandomForestClassifier(
                n_estimators=500, max_depth=18, min_samples_leaf=2,
                class_weight='balanced', random_state=42, n_jobs=-1)
            eval_clf.fit(Xtr, ytr)
            print("\nHold-out report:\n" + classification_report(yte, eval_clf.predict(Xte)))
        except ValueError:
            pass   # too few samples for stratified split

    if save:
        MODELS_DIR.mkdir(parents=True, exist_ok=True)
        with open(PLACER_MODEL_PATH, 'wb') as f:
            pickle.dump(clf, f)
        print(f"\nModel saved → {PLACER_MODEL_PATH}")

    return clf


def feature_importance(clf: RandomForestClassifier):
    FEAT_NAMES = [
        'dist_to_boundary_m', 'dist_to_gondola_m', 'dist_to_column_m',
        'is_wall_tagged', 'norm_x', 'norm_y', 'zone_area_log',
        'shelving_density', 'checkout_norm', 'zone_type_enc',
        'is_near_column', 'boundary_log', 'gondola_log',
        'tile_phase_x', 'tile_phase_y', 'n_shelving_norm',
        'shelf_depth_norm', 'is_wall_assortment', 'is_large_depth',
    ]
    ranked = sorted(zip(FEAT_NAMES, clf.feature_importances_),
                    key=lambda x: x[1], reverse=True)
    print("\nFeature importances:")
    for name, imp in ranked:
        print(f"  {name:<26} {imp:.4f}  {'█' * int(imp * 60)}")


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description="Train placement classifier")
    ap.add_argument('--bootstrap',   action='store_true',
                    help='Run DXF files through geometric pipeline and collect samples')
    ap.add_argument('--annotations', default=str(PLACEMENTS_JSONL),
                    help='JSONL file with saved placement samples')
    ap.add_argument('--synthetic',   action='store_true',
                    help='Add synthetic samples when real data is scarce')
    ap.add_argument('--n-synthetic', type=int, default=400,
                    help='Synthetic samples per class')
    ap.add_argument('--no-save',     action='store_true')
    args = ap.parse_args()

    X_all = np.empty((0, FEATURE_DIM), dtype=np.float32)
    y_all: list = []

    if args.bootstrap:
        Xb, yb = bootstrap_from_dwg()
        if len(Xb):
            X_all = np.vstack([X_all, Xb]) if len(X_all) else Xb
            y_all.extend(yb)

    Xa, ya = _jsonl_to_arrays([args.annotations])
    if len(Xa):
        X_all = np.vstack([X_all, Xa]) if len(X_all) else Xa
        y_all.extend(ya)

    if args.synthetic or len(X_all) < 200:
        print(f"Adding synthetic samples ({args.n_synthetic}/class) …")
        Xs, ys = generate_synthetic(args.n_synthetic)
        X_all = np.vstack([X_all, Xs]) if len(X_all) else Xs
        y_all.extend(ys)

    if len(X_all) == 0:
        print("No training data. Use --synthetic or --bootstrap.")
        sys.exit(1)

    clf = train(X_all, y_all, save=not args.no_save)
    feature_importance(clf)
    print(f"\nDone. {len(X_all)} samples total.")
